name: Magit-P4 tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-24.04
          - windows-latest
        emacs_version:
          - 27.2
          - 28.2
          - 29.3
          - 30.1

    steps:
    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      uses: emacs-eldev/setup-eldev@v1

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Test the project
      run: |
        eldev --packaged compile -W
        eldev --packaged test

    - name: Test the project (backwards compatibility mode)
      run: |
        eldev --packaged --old-deps compile -W
        eldev --packaged --old-deps test
