# This needs to be a separate workflow for PRs from forked repos to be reported properly,
# see https://github.com/marketplace/actions/publish-test-results#support-fork-repositories-and-dependabot-branches
name: Generate test reports
on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
permissions: {}

jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure'

    permissions:
      checks: write
      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Get saved test results
        uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d
        with:
           run_id: ${{ github.event.workflow_run.id }}
           path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/event/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/test-*.xml"
